# docker-compose.yml
version: "3.8"
services:
  mysql: # mysql container
    image: mysql:latest
    environment:
      MYSQL_DATABASE: deadlock_compose
      MYSQL_USER: deadlock_user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  phpmyadmin: # mysql admin container
    image: phpmyadmin/phpmyadmin
    ports:
      - 8002:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql